version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:pTbE,7Pjh4\\Ci6q.@34.42.255.65:5432/db
      - REDIS_URI=redis://redis:6379
      - BROKER_URI=redis://redis:6379
    volumes:
      - video-data:/app/videos
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command:
      ["celery", "-A", "src.blueprints.tasks", "worker", "--loglevel=info"]
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
  video-data: