version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:admin@34.136.103.218:5432/db
      - GOOGLE_CREDENTIALS_PATH=/app/src/sw-nube-credentials.json
      - CREDENTIALS_REQUEST=https://api.jsonbin.io/v3/b/663fa4e8e41b4d34e4f225cf
      - JWT_SECRET_KEY=your-secret-key

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
