
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y ffmpeg

WORKDIR /app

COPY /batchProcessing/videoProcessing.sh /app/videoProcessing.sh

COPY /batchProcessing/idrl.jpg  /app/idrl.jpg

ENTRYPOINT ["./videoProcessing.sh"]

