
FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y ffmpeg

WORKDIR /app

COPY videoProcessing.sh /app/videoProcessing.sh

COPY idrl.jpg  /app/idrl.jpg

ENTRYPOINT ["./videoProcessing.sh"]

